add docker
PashaRud/java-explore-with-me pull request #1
Opened 2022-11-13 16:40 UTC by PashaRud

2022-11-28 21:30 UTC, sergeymamonov requested changes

2022-11-28 21:30 UTC, sergeymamonov commented on exploreWithMe/src/main/java/ru/practicum/exploreWithMe/category/service/CategoryAdminServiceImpl.java
> +        } catch (RuntimeException e) {
А если в момент запроса отвалится сеть к БД? То в логах будет ошибка про уникальность имени.

2022-11-28 21:30 UTC, sergeymamonov commented on exploreWithMe/src/main/java/ru/practicum/exploreWithMe/request/repository/RequestRepository.java
> +//    List<Request> findByEventIdAndStatus(Long eventId, Status status);
В проекте не должно быть закомментированного кода.

2022-11-28 21:30 UTC, sergeymamonov commented on exploreWithMe/src/main/java/ru/practicum/exploreWithMe/user/repository/UserRepository.java
> +//    List<User> findByEmail(String email);
Убрать закомментированный код.

2022-11-28 21:30 UTC, sergeymamonov commented on exploreWithMe/src/main/java/ru/practicum/exploreWithMe/user/service/UserService.java
> +//    UserDto getUserById(Long id);
Закомментированный код.

2022-11-28 21:30 UTC, sergeymamonov commented on statistics/src/main/resources/schema.sql
> +    uri      varchar   NOT NULL,
Размер varchar должен быть ограничен.

2022-12-01 19:27 UTC, PashaRud commented on exploreWithMe/src/main/java/ru/practicum/exploreWithMe/category/service/CategoryAdminServiceImpl.java
> +        } catch (RuntimeException e) {
Согласен. Сузил круг ловли.

2022-12-01 20:55 UTC, sergeymamonov requested changes

2022-12-01 20:55 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/category/service/CategoryAdminServiceImpl.java
> +            throw new AlreadyExistsException("Name must be unique.");
А зачем вообще перехватывать ошибку из слоя данных и здесь кидать новую ошибку? Кинули нужную ошибку с нужным сообщением в слое данных и достаточно.

2022-12-03 05:20 UTC, sergeymamonov approved these changes
Старайтесь передавать из БД в приложение, как можно меньше данных, то есть ненужные записи нужно отсеивать с помощью запроса. Нужно стараться писать запросы так, чтобы запрос уже включал в себя всю фильтрацию. БД работает с данными быстрее чем приложение, она имеет внутренние оптимизации. Меньше данных придет через сеть быстрее.

2022-12-03 05:20 UTC, sergeymamonov commented on stats-server/src/main/java/ru/practicum/statistics/service/StatisticsServiceImpl.java
> +                uniqueHits.add(hits.stream().filter(x -> x.getIp().equals(ip)).findFirst().get());
Фильтрацию данных из БД лучше делать внутри БД, то есть включить фильтрацию в запрос.
Во-первых, БД это сделает быстрее, чем приложение, во-вторых, по сети нужно будет передать меньше данных.

2022-12-03 05:20 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/request/service/RequestPrivateServiceImpl.java
> +        } catch (RuntimeException e) {
Когда вы ловите рантайм ошибку, то это может быть все, что угодно, например отвалилась сеть к БД, а вы потом выдаете пользователю ошибку валидации, хотя его запрос валиден.

2022-12-03 05:20 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/user/service/UserServiceImpl.java
> +        } catch (RuntimeException e) {
Аналогично, можно получить где-то NPE, так как у нас неверный код, а пользователю вернуть, что у него не уникальное имя.

2022-12-05 16:13 UTC, merged